### ISSUE TITLE
AAI Integration

### ISSUE THREAD

**Issue by knodel** [pan-training/training-catalogue#11]

**Comment by servansod** [comment]
Hei @knodel 
Do we plan to integrate **UmbrellaID** as a login option? 
If yes, JFPerrin from ESRF can help set it up.

**Comment by thomasholmrod** [comment]
@servansod that's the plan. We agreed to get it up running for the e-learning platform first so that @knodel can use lessons-learned from that process. It shouldn't be necessary for users to login to the training catalogue though, but I guess it will be needed for content providers.

**Comment by knodel** [comment]
Authentication with UmbrellaID is now possible in our catalogue at [pan-training.eu](pan-training.eu). I will also change the order of the login options in one of the next updates.

**Comment by knodel** [comment]
Login to an existing pan-training account or without a pan-training account is possible with UmbrellaID. The login page is redesigned  to bring UmbrellaID more to the foreground.
