### ISSUE TITLE
e-Learning tab still necessary?

### ISSUE THREAD

**Issue by knodel** [pan-training/training-catalogue#12]
Is it necessary? What can be the difference between material and e-learning? Should we sync the PaN-learning content here?

**Comment by thomasholmrod** [comment]
to my understading 'material' is external ones. You should not have to login to view the links to external material. Courses in the e-learning paltform are personal - you can for instance take a quiz and your results will be stored. You can also use Jupyter in relation to courses.

**Comment by thomasholmrod** [comment]
If you mean, that each course in the e-learning platform should have an entry in the training catalogue, I agree we should try to sync

**Comment by knodel** [comment]
Yes, that should be possible with the scrapers I forked from TeSS (https://github.com/pan-training/training-catalogue-scrapers).
