### ISSUE TITLE
Monitor number of unique visitors?

### ISSUE THREAD

**Issue by servansod** [pan-training/training-catalogue#20]
In both ExPaNDS WP5 and PaNOSC WP8 we have the following KPI: "Number of unique visitors to the training portal"

If it is still a KPI you intend to follow, we should plan to implement a hit counter in the catalogue, if there is not already one?

**Comment by knodel** [comment]
Good point! Thanks @servansod ! We can integrate https://github.com/biola/punching_bag or something similar...

**Comment by knodel** [comment]
![Screen Shot 2021-12-10 at 11 16 40](https://user-images.githubusercontent.com/18582732/145557804-92cb9052-6aca-4330-aa04-ea93d2b59c9a.png)

Available since this week! @antoinepado can we give @servansod access to the site via her curator role?

**Comment by antoinepado** [comment]
Sure, just need to change the config/routes.rb lines giving access to blazer.
Specifically these lines:

```
  authenticate :user, lambda { |u| u.is_admin? || u.is_curator?  } do
    mount Blazer::Engine, at: "blazer"   
  end
```

**|| u.is_curator?** is added.

**Comment by knodel** [comment]
as simple as I thought ;-) Thanks @antoinepado ! 
@servansod you can now access the Dashboards at https://pan-training.hzdr.de/blazer/dashboards/1-overview
