### ISSUE TITLE
Open Graph metadata is still showing Elixir's TeSS

### ISSUE THREAD

**Issue by servansod** [pan-training/training-catalogue#31]
Small fix but I just noticed that the metadata property for OG are still the ones from Elixir. I noticed it while pasting the link to [pan-training.hzdr.de](https://pan-training.hzdr.de/) in Mattermost.
It should be updated to PaN, [for example in this file](https://github.com/pan-training/training-catalogue/blob/3ec198e6dc01f2798cbd749966c63bf343c5ca55/app/views/common/_default_og.html.erb):
```
<%= tag(:meta, property: "og:title", content: "TeSS Training eSupport System" ) %>
<%= tag(:meta, property: "og:description", content: "Browse, discover and organise Life science training resources aggregated from ELIXIR nodes and other providers" ) %>
<%= tag(:meta, property: "og:image", content: asset_url("ELIXIR_TeSS_logo_normal.png") ) %>
```

**Comment by knodel** [comment]
![Screen Shot 2021-11-23 at 17 01 36](https://user-images.githubusercontent.com/18582732/143059359-67b67fcf-40e2-4bce-9f54-dd1630e76dae.png)
