### ISSUE TITLE
Front-page redesign joint PaN appearance 

### ISSUE THREAD

**Issue by knodel** [pan-training/training-catalogue#36]
We need a more modern front-page. The design suggestion from @moving-northwards is here: https://pan-learning.org/moodle/customfiles/alldark 

Next steps: clean up old CSS stuff, embed new css and configure front-page code.

**Comment by knodel** [comment]
And here is the first draft of your design @moving-northwards implemented on our development system. 

![PaN-Training-Frontpage-2022](https://user-images.githubusercontent.com/18582732/148201217-4ce01bc7-7dfd-4f4c-87d9-c34e7aa06a25.png)

**Comment by knodel** [comment]
But I think we need maybe an additional blue box to visually separate the E-learning section from the content. 🤔

**Comment by UweKonrad** [comment]
Its nice and looks fresh and clear, thanks. The typos are already done (e.g. browse **by** the institute providing, portal for photon &**amp**...)?
The small menu at the top is somewhat redundant to the icons below the search, but it is not distracting.
If the (coming) events catalogue is empty (as now) it does not look very promising. Does it make sense to show some of the latest in this case?
The provider list is impressive!

**Comment by UweKonrad** [comment]
In the Materials section I would propose to put the Ressource Type more upwards, it is now at the very end, is that possible?

**Comment by UweKonrad** [comment]
I am not sure that it will be better with another blue box?

**Comment by moving-northwards** [comment]
Would it be possible to instead of a blue line have the background for the content dark but keep each box white? Something like this:
![image](https://user-images.githubusercontent.com/32637035/149531361-d098349f-ead4-4eb8-89fe-1b27d147c52a.png)

**Comment by knodel** [comment]
The new front-page is in production
