### ISSUE TITLE
Synchronize the training catalogue with pan-learning.org

### ISSUE THREAD

**Issue by knodel** [pan-training/training-catalogue#7]
On our side we have an web API to create new entries, but on the moodle side?

**Comment by knodel** [comment]
Added #22 and #23 as dependencies

**Comment by antoinepado** [comment]
@willend What are the next steps in order to activate the webservices on the [e-learning platform](https://pan-learning.org/) ? 
Here's a document with some instructions that might be useful.
[moodle.odt](https://github.com/pan-training/training-catalogue/files/7244300/moodle.odt)

**Comment by willend** [comment]
@antoinepado my understanding is that the strategy is to implement a solution "in the opposite direction", meaning to "harvest" course-information from pan-learning.org, making it available in the training catalogue. 

But I am sure @knodel has the best overview of this area. :)

**Comment by knodel** [comment]
Okay, in the end both directions are possible. We can harvest the information with our catalogue (moodle API required) or we can push the course information directly from pan-learning.org into the training catalogue (maybe the more efficient way...). 
Next week our catalogue API should be ready and we can discuss both approaches maybe in the technical meeting next Wednesday? @willend can you please invite @antoinepado for our Wednesday meetings?

**Comment by willend** [comment]
@knodel good point, I will invite @antoinepado in the forthcoming meetings!
