### ISSUE TITLE
Guiding the user to the catalogue or the e-learning platform.

### ISSUE THREAD

**Issue by antoinepado** [pan-training/training-catalogue#73]
On the front page, guide the user to the relevant place depending on his needs.
If the user wants to create a material, redirect him to the e-learning platform where  he will be able to create a course.
If he wants to share an existing material, redirect him to the catalogue's register material page.

This is an idea that came forward following the "Brainstorming on the platform development" discussion that took place at the [PaNOSC&ExPANDS Face to Face Meeting](https://indico.eli-laser.eu/event/12/).

**Comment by knodel** [comment]
Here is a first draft of a decision tree to guide the user to the most relevant system for the content.

On the front-page we have a button "Register new content":
<img width="1405" alt="Screen Shot 2022-09-06 at 13 50 20" src="https://user-images.githubusercontent.com/18582732/188639646-85bb0c92-4693-4f5d-880b-02c5d5655b96.png">

And the button brings the user to a simple decision tree:
<img width="1405" alt="Screen Shot 2022-09-06 at 13 51 26" src="https://user-images.githubusercontent.com/18582732/188639859-bcc76354-613d-4325-aa09-61da3e3626cd.png">

On the subpages: material, events or workflow the specific add content buttons remain.

**Comment by knodel** [comment]
What do you think @willend @arm61 ?

**Comment by willend** [comment]
@knodel looks good to me, the only thing that comes to mind is that it would be good to flash we can run Jupyter notebooks. (At the moment purely through a Moodle hook.)

Maybe simply add (provides Jupyter support) to the Moodle "button"?

**Comment by knodel** [comment]
@willend Good point, I will add the Jupyter support.

**Comment by arm61** [comment]
What page does the "Create E-learning course on pan-learning" direct to?

**Comment by willend** [comment]
@arm61 good point. That should probably link to either a documentation-page or to some sort of feedback-form. 

Fact of the matter is that the process is quite hand-held...

**Comment by arm61** [comment]
Yeah, it is something that I would like to investigate for the e-learning platform, currently the standard way to create a course is to email admin@pan-learning.org right?

**Comment by willend** [comment]
Yes, emailing "ought to" work - or use https://sim.e-neutrons.esss.dk/contact (effectively the same).

**Comment by knodel** [comment]
Okay, maybe we can automate the creation process or guide a user to a request from to semi-automate it? We can also create such a form in PaN-Training if necessary...

**Comment by willend** [comment]
@knodel having it in the main pan-training domain makes lots of sense. Let's discuss this e.g. in one of the next "tech" meetings?

(I can not take part myself this week though.)

**Comment by arm61** [comment]
Yeah hosting it on pan-learning will be nice. I will try and outline what content would be in such a form for the meeting next week.

**Comment by knodel** [comment]
@willend @arm61 Sounds good. I will be available the next weeks and we can discuss what we can do :+1:
