### ISSUE TITLE
Unhide direct login/register page 

### ISSUE THREAD

**Issue by antoinepado** [pan-training/training-catalogue#82]
Currently the direct login/register page is hidden in order to encourage users to use umbrellaID.
What if they do not have one and can't have one?

**Comment by knodel** [comment]
At the moment we have both on the same level, but now it is not very intuitive... Last week I tried to log in with my UmbrellaID credentials on the right side. Any ideas to improve the page @antoinepado ?
<img width="1414" alt="Screenshot 2022-11-16 at 17 35 47" src="https://user-images.githubusercontent.com/18582732/202239382-5ff4b9b5-2c0d-4451-ac91-384d2cfbdf17.png">

**Comment by knodel** [comment]
Okay... I. can replace `Direct Catalog Login` with `PaN-training Login` and show with a button that the UmbralllaID Logo is clickable.

**Comment by knodel** [comment]
![Screenshot 2022-11-23 at 17 19 42](https://user-images.githubusercontent.com/18582732/203596556-1b803bb0-4433-4644-87fa-5a475cbb9c6a.png)
